// kv_lifecycle_guard.v
// Verilog-2001 boundary for the KV page lifecycle guard.
//
// IP Integrator refuses a SystemVerilog file as a BD module reference
// (ERROR [filemgmt 56-195]). This shim also renames the global signals to
// the AXI spec names ACLK/ARESETn so IPI auto-associates the clock.
//
// The dbg_* ports are NAMED PER-FIELD debug outputs, one ILA probe each,
// so Hardware Manager shows them by name and each can be triggered on
// individually. Generated from the real SV header, never hand-transcribed.

module kv_lifecycle_guard (
  input  wire aclk,
  input  wire aresetn,
  input  wire [11:0] s_axi_awaddr,
  input  wire [2:0] s_axi_awprot,
  input  wire s_axi_awvalid,
  output wire s_axi_awready,
  input  wire [31:0] s_axi_wdata,
  input  wire [3:0] s_axi_wstrb,
  input  wire s_axi_wvalid,
  output wire s_axi_wready,
  output wire [1:0] s_axi_bresp,
  output wire s_axi_bvalid,
  input  wire s_axi_bready,
  input  wire [11:0] s_axi_araddr,
  input  wire [2:0] s_axi_arprot,
  input  wire s_axi_arvalid,
  output wire s_axi_arready,
  output wire [31:0] s_axi_rdata,
  output wire [1:0] s_axi_rresp,
  output wire s_axi_rvalid,
  input  wire s_axi_rready,
  output wire [3:0] m_axi_arid,
  output wire [39:0] m_axi_araddr,
  output wire [7:0] m_axi_arlen,
  output wire [2:0] m_axi_arsize,
  output wire [1:0] m_axi_arburst,
  output wire m_axi_arlock,
  output wire [3:0] m_axi_arcache,
  output wire [2:0] m_axi_arprot,
  output wire [3:0] m_axi_arqos,
  output wire m_axi_arvalid,
  input  wire m_axi_arready,
  input  wire [3:0] m_axi_rid,
  input  wire [127:0] m_axi_rdata,
  input  wire [1:0] m_axi_rresp,
  input  wire m_axi_rlast,
  input  wire m_axi_rvalid,
  output wire m_axi_rready,
  output wire dbg_rstn,
  output wire [15:0] dbg_heartbeat,
  output wire [7:0] dbg_refcount,
  output wire [7:0] dbg_reservation,
  output wire [5:0] dbg_inflight,
  output wire [3:0] dbg_fill_pending,
  output wire [7:0] dbg_generation,
  output wire [7:0] dbg_exp_generation,
  output wire [5:0] dbg_slot,
  output wire [5:0] dbg_phys,
  output wire dbg_reuse_req,
  output wire dbg_reuse_grant,
  output wire dbg_reuse_refused,
  output wire dbg_stale,
  output wire dbg_payload_mm,
  output wire dbg_evictable,
  output wire [1:0] dbg_outstanding,
  output wire [15:0] dbg_ar_wait,
  output wire [15:0] dbg_rd_latency,
  output wire [15:0] dbg_rd_latency_max,
  output wire [7:0] dbg_sticky,
  output wire [195:0] dbg_probe
);

  lifecycle_guard_top u_core (
    .clk                 (aclk),
    .rst_n               (aresetn),
    .s_axi_awaddr        (s_axi_awaddr),
    .s_axi_awprot        (s_axi_awprot),
    .s_axi_awvalid       (s_axi_awvalid),
    .s_axi_awready       (s_axi_awready),
    .s_axi_wdata         (s_axi_wdata),
    .s_axi_wstrb         (s_axi_wstrb),
    .s_axi_wvalid        (s_axi_wvalid),
    .s_axi_wready        (s_axi_wready),
    .s_axi_bresp         (s_axi_bresp),
    .s_axi_bvalid        (s_axi_bvalid),
    .s_axi_bready        (s_axi_bready),
    .s_axi_araddr        (s_axi_araddr),
    .s_axi_arprot        (s_axi_arprot),
    .s_axi_arvalid       (s_axi_arvalid),
    .s_axi_arready       (s_axi_arready),
    .s_axi_rdata         (s_axi_rdata),
    .s_axi_rresp         (s_axi_rresp),
    .s_axi_rvalid        (s_axi_rvalid),
    .s_axi_rready        (s_axi_rready),
    .m_axi_arid          (m_axi_arid),
    .m_axi_araddr        (m_axi_araddr),
    .m_axi_arlen         (m_axi_arlen),
    .m_axi_arsize        (m_axi_arsize),
    .m_axi_arburst       (m_axi_arburst),
    .m_axi_arlock        (m_axi_arlock),
    .m_axi_arcache       (m_axi_arcache),
    .m_axi_arprot        (m_axi_arprot),
    .m_axi_arqos         (m_axi_arqos),
    .m_axi_arvalid       (m_axi_arvalid),
    .m_axi_arready       (m_axi_arready),
    .m_axi_rid           (m_axi_rid),
    .m_axi_rdata         (m_axi_rdata),
    .m_axi_rresp         (m_axi_rresp),
    .m_axi_rlast         (m_axi_rlast),
    .m_axi_rvalid        (m_axi_rvalid),
    .m_axi_rready        (m_axi_rready),
    .dbg_rstn            (dbg_rstn),
    .dbg_heartbeat       (dbg_heartbeat),
    .dbg_refcount        (dbg_refcount),
    .dbg_reservation     (dbg_reservation),
    .dbg_inflight        (dbg_inflight),
    .dbg_fill_pending    (dbg_fill_pending),
    .dbg_generation      (dbg_generation),
    .dbg_exp_generation  (dbg_exp_generation),
    .dbg_slot            (dbg_slot),
    .dbg_phys            (dbg_phys),
    .dbg_reuse_req       (dbg_reuse_req),
    .dbg_reuse_grant     (dbg_reuse_grant),
    .dbg_reuse_refused   (dbg_reuse_refused),
    .dbg_stale           (dbg_stale),
    .dbg_payload_mm      (dbg_payload_mm),
    .dbg_evictable       (dbg_evictable),
    .dbg_outstanding     (dbg_outstanding),
    .dbg_ar_wait         (dbg_ar_wait),
    .dbg_rd_latency      (dbg_rd_latency),
    .dbg_rd_latency_max  (dbg_rd_latency_max),
    .dbg_sticky          (dbg_sticky),
    .o_ila_probe         (dbg_probe)
  );

endmodule
